# Programs that start when you log in
exec-once = noctalia
exec-once = waybar
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet --indicator

# Conky (floating stats of my PC)
# Start at login, and also after a config reload if it is not running.
exec-once = conky -c /home/jonat/.config/conky/conky.conf
exec = pgrep -x conky > /dev/null || conky -c /home/jonat/.config/conky/conky.conf
