# Appearance: gaps, borders, rounding, opacity, blur, shadows
general {
    gaps_in = 4
    gaps_out = 15
    border_size = 3
    col.active_border = rgb(89b4fa)
    col.inactive_border = rgb(313244)
    layout = dwindle
}

decoration {
    rounding = 7
    active_opacity = 0.97
    inactive_opacity = 0.85

    blur {
        enabled = true
        size = 3
        passes = 1
    }

    shadow {
        enabled = true
        range = 15
        color = rgba(00000099)
    }
}
